/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal1;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class actualizarproducto extends javax.swing.JPanel {
 conector conecta = new conector();
        Connection con = conecta.getConexion();
    /**
     * Creates new form actualizarproducto
     */
    public actualizarproducto() {
        initComponents();
        mostrar("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        id_producto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nombre_producto = new javax.swing.JTextField();
        cantidad_producto = new javax.swing.JTextField();
        referencia_producto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        stock_producto = new javax.swing.JTextField();
        precio_total_producto = new javax.swing.JTextField();
        calcular = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        buscar = new javax.swing.JTextField();
        rdb_cantidad = new javax.swing.JRadioButton();
        btn_aceptar = new javax.swing.JButton();
        rdb_identificacion = new javax.swing.JRadioButton();
        rdb_nombres = new javax.swing.JRadioButton();
        rdb_referencia = new javax.swing.JRadioButton();
        rdb_stock = new javax.swing.JRadioButton();
        tlabel1 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_datos = new javax.swing.JTable();

        jMenuItem1.setText("Modificar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("eliminar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Stock del producto");

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Limpiar.png"))); // NOI18N
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Cantidad del producto");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Precio total del producto");

        id_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_productoActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Codigo del producto");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Nombre del producto");

        stock_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stock_productoActionPerformed(evt);
            }
        });

        calcular.setBackground(new java.awt.Color(255, 255, 255));
        calcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Calcular.png"))); // NOI18N
        calcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Referencia del producto");

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/registrar.png"))); // NOI18N
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        buscar.setComponentPopupMenu(jPopupMenu1);
        buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarKeyReleased(evt);
            }
        });

        rdb_cantidad.setBackground(new java.awt.Color(255, 255, 255));
        rdb_cantidad.setText("Cantidad");
        rdb_cantidad.setComponentPopupMenu(jPopupMenu1);
        rdb_cantidad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rdb_cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_cantidadActionPerformed(evt);
            }
        });

        btn_aceptar.setBackground(new java.awt.Color(255, 255, 255));
        btn_aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Aceptar.png"))); // NOI18N
        btn_aceptar.setComponentPopupMenu(jPopupMenu1);
        btn_aceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        rdb_identificacion.setBackground(new java.awt.Color(255, 255, 255));
        rdb_identificacion.setText("ID");
        rdb_identificacion.setComponentPopupMenu(jPopupMenu1);
        rdb_identificacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rdb_identificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_identificacionActionPerformed(evt);
            }
        });

        rdb_nombres.setBackground(new java.awt.Color(255, 255, 255));
        rdb_nombres.setText("Nombres");
        rdb_nombres.setComponentPopupMenu(jPopupMenu1);
        rdb_nombres.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rdb_nombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_nombresActionPerformed(evt);
            }
        });

        rdb_referencia.setBackground(new java.awt.Color(255, 255, 255));
        rdb_referencia.setText("Referencia");
        rdb_referencia.setComponentPopupMenu(jPopupMenu1);
        rdb_referencia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rdb_referencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_referenciaActionPerformed(evt);
            }
        });

        rdb_stock.setBackground(new java.awt.Color(255, 255, 255));
        rdb_stock.setText("Stock");
        rdb_stock.setComponentPopupMenu(jPopupMenu1);
        rdb_stock.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tlabel1.setText("Valor a buscar:");
        tlabel1.setComponentPopupMenu(jPopupMenu1);
        tlabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Actualizar.png"))); // NOI18N
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        Tbl_datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tbl_datos.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(Tbl_datos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(precio_total_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(nombre_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(referencia_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(id_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(cantidad_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(stock_producto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tlabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(btn_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rdb_identificacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdb_nombres)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdb_referencia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdb_stock)
                                .addGap(13, 13, 13)
                                .addComponent(rdb_cantidad)))
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nombre_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(referencia_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(stock_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(cantidad_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(precio_total_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdb_identificacion)
                            .addComponent(rdb_nombres)
                            .addComponent(rdb_referencia)
                            .addComponent(rdb_cantidad)
                            .addComponent(rdb_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tlabel1)
                            .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void id_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_productoActionPerformed

    private void stock_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stock_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stock_productoActionPerformed

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        int n1, n2, result = 0;
        n1 = Integer.parseInt(stock_producto.getText());
        n2 = Integer.parseInt(cantidad_producto.getText());

        result = n1*n2;
        precio_total_producto.setText("" + result);
    }//GEN-LAST:event_calcularActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            // TODO add your handling code here:
            PreparedStatement pps = con.prepareStatement("INSERT INTO producto(ID_PRODUCTO, NOMBRE_PRODUCTO, REFERENCIAS_DEL_PRODUCTO, STOCK_DEL_PRODUCTO, CANTIDAD_PRODUCTO, TOTAL_PRECIO_PRODUCTO) VALUES (?,?,?,?,?,?)");
            pps.setString(1, id_producto.getText());
            pps.setString(2, nombre_producto.getText());
            pps.setString(3, referencia_producto.getText());
            pps.setString(4, stock_producto.getText());
            pps.setString(5, cantidad_producto.getText());
            pps.setString(6, precio_total_producto.getText());
            pps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Cita guardada exitosamente");

        } catch (SQLException ex) {
            Logger.getLogger(producto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarKeyReleased

    private void rdb_cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdb_cantidadActionPerformed

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        // TODO add your handling code here:
        if(rdb_identificacion.isSelected()){
            mostrar(buscar.getText());
        }else if(rdb_nombres.isSelected()){
            mostrar2(buscar.getText());
        }else if (rdb_referencia.isSelected()){
            mostrar3(buscar.getText());
        }else if (rdb_cantidad.isSelected()){
            mostrar4(buscar.getText());
        }else if(rdb_stock.isSelected()){
            mostrar5(buscar.getText());
        }else{
            mostrar6(buscar.getText());
        }
    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void rdb_identificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_identificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdb_identificacionActionPerformed

    private void rdb_nombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_nombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdb_nombresActionPerformed

    private void rdb_referenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_referenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdb_referenciaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int fila = Tbl_datos.getSelectedRow();
        if(fila>=0){
            id_producto.setText(Tbl_datos.getValueAt(fila, 0).toString());
            nombre_producto.setText(Tbl_datos.getValueAt(fila, 1).toString());
            referencia_producto.setText(Tbl_datos.getValueAt(fila, 2).toString());
            stock_producto.setText(Tbl_datos.getValueAt(fila, 3).toString());
            cantidad_producto.setText(Tbl_datos.getValueAt(fila, 4).toString());
            precio_total_producto.setText(Tbl_datos.getValueAt(fila, 5).toString());
        }
        else{
            JOptionPane.showMessageDialog(null, "No fue seleccionada");
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try {
             PreparedStatement pps = con.prepareStatement("UPDATE producto SET NOMBRE_PRODUCTO='"+nombre_producto.getText()+"',REFERENCIAS_DEL_PRODUCTO='"+referencia_producto.getText()+"',STOCK_DEL_PRODUCTO='"+stock_producto.getText()+"',CANTIDAD_PRODUCTO='"+cantidad_producto.getText()+"',TOTAL_PRECIO_PRODUCTO='"+precio_total_producto.getText()+"' WHERE ID_PRODUCTO='"+id_producto.getText()+"'");
             pps.executeUpdate();
             mostrar("");
  
        } catch (SQLException ex) {
            Logger.getLogger(producto.class.getName()).log(Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        int fila = Tbl_datos.getSelectedRow();
        String id="";
        id=Tbl_datos.getValueAt(fila, 0).toString();
        
        try {
            PreparedStatement pps = con.prepareStatement("DELETE FROM producto WHERE ID_PRODUCTO='"+id+"'");
            pps.executeUpdate();
            mostrar("");
        } catch (SQLException ex) {
            Logger.getLogger(producto.class.getName()).log(Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        id_producto.setText("");
        nombre_producto.setText("");
        referencia_producto.setText("");
        stock_producto.setText("");
        cantidad_producto.setText("");
        precio_total_producto.setText("");
    }//GEN-LAST:event_jButton8ActionPerformed
public  void mostrar(String nombre){
  DefaultTableModel  modelo = new DefaultTableModel();
  modelo.addColumn("Id del producto");
        modelo.addColumn("Nombre del producto");
        modelo.addColumn("Referencia del producto");
        modelo.addColumn("Stock del producto");
        modelo.addColumn("Cantidad del producto");
        modelo.addColumn("total del precio");
       Tbl_datos.setModel(modelo);
        String sql="";
        if(nombre.equals("")){
            sql="SELECT * FROM `producto`";
            
            
        
        }else{
            sql="SELECT * FROM `producto` WHERE ID_PRODUCTO  like'%"+nombre+"%'";
        }
        String usuarios[]=new String[6];
        Statement set;
    try {
        set = con.createStatement();
        ResultSet result=set.executeQuery(sql);
        while(result.next()){
            usuarios[0]=result.getString(1);
            usuarios[1]=result.getString(2);
            usuarios[2]=result.getString(3);
            usuarios[3]=result.getString(4);
            usuarios[4]=result.getString(5);
            usuarios[5]=result.getString(6);
            modelo.addRow(usuarios);
        }
        Tbl_datos.setModel(modelo);
    } catch (SQLException ex) {
        Logger.getLogger(inventario.class.getName()).log(Level.SEVERE, null, ex);
    }
        
}
public  void mostrar2(String nombre){
  DefaultTableModel  modelo = new DefaultTableModel();
  modelo.addColumn("Id del producto");
        modelo.addColumn("Nombre del producto");
        modelo.addColumn("Referencia del producto");
        modelo.addColumn("Stock del producto");
        modelo.addColumn("Cantidad del producto");
        modelo.addColumn("total del precio");
       Tbl_datos.setModel(modelo);
        String sql="";
        if(nombre.equals("")){
            sql="SELECT * FROM `producto`";
            
            
        
        }else{
            sql="SELECT * FROM `producto` WHERE NOMBRE_PRODUCTO like'%"+nombre+"%'";
        }
        String usuarios[]=new String[6];
        Statement set;
    try {
        set = con.createStatement();
        ResultSet result=set.executeQuery(sql);
        while(result.next()){
            usuarios[0]=result.getString(1);
            usuarios[1]=result.getString(2);
            usuarios[2]=result.getString(3);
            usuarios[3]=result.getString(4);
            usuarios[4]=result.getString(5);
            usuarios[5]=result.getString(6);
            modelo.addRow(usuarios);
        }
        Tbl_datos.setModel(modelo);
    } catch (SQLException ex) {
        Logger.getLogger(inventario.class.getName()).log(Level.SEVERE, null, ex);
    }
        
}
public  void mostrar3(String nombre){
  DefaultTableModel  modelo = new DefaultTableModel();
modelo.addColumn("Id del producto");
        modelo.addColumn("Nombre del producto");
        modelo.addColumn("Referencia del producto");
        modelo.addColumn("Stock del producto");
        modelo.addColumn("Cantidad del producto");
        modelo.addColumn("total del precio");
       Tbl_datos.setModel(modelo);
        String sql="";
        if(nombre.equals("")){
            sql="SELECT * FROM `producto`";
            
            
        
        }else{
            sql="SELECT * FROM `producto` WHERE REFERENCIAS_DEL_PRODUCTO like'%"+nombre+"%'";
        }
        String usuarios[]=new String[6];
        Statement set;
    try {
        set = con.createStatement();
        ResultSet result=set.executeQuery(sql);
        while(result.next()){
            usuarios[0]=result.getString(1);
            usuarios[1]=result.getString(2);
            usuarios[2]=result.getString(3);
            usuarios[3]=result.getString(4);
            usuarios[4]=result.getString(5);
            usuarios[5]=result.getString(6);
            modelo.addRow(usuarios);
        }
        Tbl_datos.setModel(modelo);
    } catch (SQLException ex) {
        Logger.getLogger(inventario.class.getName()).log(Level.SEVERE, null, ex);
    }
        
}
public  void mostrar4(String nombre){
  DefaultTableModel  modelo = new DefaultTableModel();
modelo.addColumn("Id del producto");
        modelo.addColumn("Nombre del producto");
        modelo.addColumn("Referencia del producto");
        modelo.addColumn("Stock del producto");
        modelo.addColumn("Cantidad del producto");
        modelo.addColumn("total del precio");
       Tbl_datos.setModel(modelo);
        String sql="";
        if(nombre.equals("")){
            sql="SELECT * FROM `producto`";
            
            
        
        }else{
            sql="SELECT * FROM `producto`WHERE CANTIDAD_PRODUCTO like'%"+nombre+"%'";
        }
        String usuarios[]=new String[6];
        Statement set;
    try {
        set = con.createStatement();
        ResultSet result=set.executeQuery(sql);
        while(result.next()){
            usuarios[0]=result.getString(1);
            usuarios[1]=result.getString(2);
            usuarios[2]=result.getString(3);
            usuarios[3]=result.getString(4);
            usuarios[4]=result.getString(5);
            usuarios[5]=result.getString(6);
            modelo.addRow(usuarios);
        }
        Tbl_datos.setModel(modelo);
    } catch (SQLException ex) {
        Logger.getLogger(inventario.class.getName()).log(Level.SEVERE, null, ex);
    }
        
}
public  void mostrar5(String nombre){
  DefaultTableModel  modelo = new DefaultTableModel();
modelo.addColumn("Id del producto");
        modelo.addColumn("Nombre del producto");
        modelo.addColumn("Referencia del producto");
        modelo.addColumn("Stock del producto");
        modelo.addColumn("Cantidad del producto");
        modelo.addColumn("total del precio");
       Tbl_datos.setModel(modelo);
        String sql="";
        if(nombre.equals("")){
            sql="SELECT * FROM `producto`";
            
            
        
        }else{
            sql="SELECT * FROM `producto` WHERE STOCK_DEL_PRODUCTO like'%"+nombre+"%'";
        }
        String usuarios[]=new String[6];
        Statement set;
    try {
        set = con.createStatement();
        ResultSet result=set.executeQuery(sql);
        while(result.next()){
            usuarios[0]=result.getString(1);
            usuarios[1]=result.getString(2);
            usuarios[2]=result.getString(3);
            usuarios[3]=result.getString(4);
            usuarios[4]=result.getString(5);
            usuarios[5]=result.getString(6);
            modelo.addRow(usuarios);
        }
        Tbl_datos.setModel(modelo);
    } catch (SQLException ex) {
        Logger.getLogger(inventario.class.getName()).log(Level.SEVERE, null, ex);
    }
        
}
public  void mostrar6(String nombre){
  DefaultTableModel  modelo = new DefaultTableModel();
modelo.addColumn("Id del producto");
        modelo.addColumn("Nombre del producto");
        modelo.addColumn("Referencia del producto");
        modelo.addColumn("Stock del producto");
        modelo.addColumn("Cantidad del producto");
        modelo.addColumn("total del precio");
       Tbl_datos.setModel(modelo);
        String sql="";
        if(nombre.equals("")){
            sql="SELECT * FROM `producto`";
            
            
        
        }else{
            sql="SELECT * FROM `producto`";
        }
        String usuarios[]=new String[6];
        Statement set;
    try {
        set = con.createStatement();
        ResultSet result=set.executeQuery(sql);
        while(result.next()){
            usuarios[0]=result.getString(1);
            usuarios[1]=result.getString(2);
            usuarios[2]=result.getString(3);
            usuarios[3]=result.getString(4);
            usuarios[4]=result.getString(5);
            usuarios[5]=result.getString(6);
            modelo.addRow(usuarios);
        }
        Tbl_datos.setModel(modelo);
    } catch (SQLException ex) {
        Logger.getLogger(inventario.class.getName()).log(Level.SEVERE, null, ex);
    }
        
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tbl_datos;
    public javax.swing.JButton btn_aceptar;
    public javax.swing.JTextField buscar;
    private javax.swing.JButton calcular;
    private javax.swing.JTextField cantidad_producto;
    private javax.swing.JTextField id_producto;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombre_producto;
    private javax.swing.JTextField precio_total_producto;
    public javax.swing.JRadioButton rdb_cantidad;
    public javax.swing.JRadioButton rdb_identificacion;
    public javax.swing.JRadioButton rdb_nombres;
    public javax.swing.JRadioButton rdb_referencia;
    public javax.swing.JRadioButton rdb_stock;
    private javax.swing.JTextField referencia_producto;
    private javax.swing.JTextField stock_producto;
    public javax.swing.JLabel tlabel1;
    // End of variables declaration//GEN-END:variables
}
