/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal1;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class compra1 extends javax.swing.JPanel {
 conector conecta = new conector();
        Connection con = conecta.getConexion();
    /**
     * Creates new form compra1
     */
    public compra1() {
        initComponents();
        mostrar("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        idcompra = new javax.swing.JLabel();
        dias_compra = new javax.swing.JTextField();
        idproducto = new javax.swing.JLabel();
        estado_compra = new javax.swing.JTextField();
        idproveedor = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        cantidadcompra = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        diascompra = new javax.swing.JLabel();
        estadocompra = new javax.swing.JLabel();
        id_producto = new javax.swing.JTextField();
        id_compra = new javax.swing.JTextField();
        id_proveedor = new javax.swing.JTextField();
        cantidad_compra = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_datos = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();

        jMenuItem1.setText("Modificar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("eliminar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        idcompra.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        idcompra.setText("Id del producto");

        dias_compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dias_compraActionPerformed(evt);
            }
        });

        idproducto.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        idproducto.setText("Id de la compra");

        idproveedor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        idproveedor.setText("Id del proveedor");

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/comprar.png"))); // NOI18N
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        cantidadcompra.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        cantidadcompra.setText("Canctidad a comprar");

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Limpiar.png"))); // NOI18N
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        diascompra.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        diascompra.setText("Dias de la compra");

        estadocompra.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        estadocompra.setText("Estado de la compra");

        id_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_productoActionPerformed(evt);
            }
        });

        cantidad_compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad_compraActionPerformed(evt);
            }
        });

        Tbl_datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tbl_datos.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(Tbl_datos);

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Actualizar.png"))); // NOI18N
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cantidadcompra)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idproveedor)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(estadocompra))
                                    .addComponent(idcompra)
                                    .addComponent(diascompra)))
                            .addComponent(idproducto))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(dias_compra, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cantidad_compra, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id_proveedor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id_producto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id_compra, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(estado_compra, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id_compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idproducto))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idcompra, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idproveedor))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cantidad_compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cantidadcompra))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dias_compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(diascompra))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(estado_compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(estadocompra))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dias_compraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dias_compraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dias_compraActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
          try {
         // TODO add your handling code here:
         PreparedStatement pps = con.prepareStatement("INSERT INTO compra(ID_COMPRA,	ID_PRODUCTO,	ID_PROVEEDOR,	CANTIDAD_COMPRA,	DIA_REABASTECIOMIENTO,	ESTADO_DE_LA_COMPRA) VALUES (?,?,?,?,?,?)");
         pps.setString(1, id_compra.getText());
         pps.setString(2, id_producto.getText());
         pps.setString(3, id_proveedor.getText());
         pps.setString(4, cantidad_compra.getText());
         pps.setString(5, dias_compra.getText());
         pps.setString(6, estado_compra.getText());
         pps.executeUpdate();
         JOptionPane.showMessageDialog(null, "Cita guardada exitosamente");
         
     } catch (SQLException ex) {
         Logger.getLogger(producto.class.getName()).log(Level.SEVERE, null, ex);
     }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void id_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_productoActionPerformed

    private void cantidad_compraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad_compraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad_compraActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       id_compra.setText("");
       id_producto.setText("");
       id_proveedor.setText("");
       cantidad_compra.setText("");
       dias_compra.setText("");
       estado_compra.setText("");
       
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try {
             PreparedStatement pps = con.prepareStatement("UPDATE compra SET CANTIDAD_COMPRA='"+cantidad_compra.getText()+"',DIA_REABASTECIOMIENTO='"+dias_compra.getText()+"',ESTADO_DE_LA_COMPRA='"+estado_compra.getText()+"' WHERE ID_COMPRA='"+id_compra.getText()+"'");
             pps.executeUpdate();
             mostrar("");
  
        } catch (SQLException ex) {
            Logger.getLogger(producto.class.getName()).log(Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int fila = Tbl_datos.getSelectedRow();
        if(fila>=0){
            id_compra.setText(Tbl_datos.getValueAt(fila, 0).toString());
            id_producto.setText(Tbl_datos.getValueAt(fila, 1).toString());
            id_proveedor.setText(Tbl_datos.getValueAt(fila, 2).toString());
            cantidad_compra.setText(Tbl_datos.getValueAt(fila, 3).toString());
            dias_compra.setText(Tbl_datos.getValueAt(fila, 4).toString());
            estado_compra.setText(Tbl_datos.getValueAt(fila, 5).toString());

        }
        else{
            JOptionPane.showMessageDialog(null, "No fue seleccionada");
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        int fila = Tbl_datos.getSelectedRow();
        String id="";
        id=Tbl_datos.getValueAt(fila, 0).toString();

        try {
            PreparedStatement pps = con.prepareStatement("DELETE FROM producto WHERE ID_PRODUCTO='"+id+"'");
            pps.executeUpdate();
            mostrar("");
        } catch (SQLException ex) {
            Logger.getLogger(producto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed
public  void mostrar(String nombre){
  DefaultTableModel  modelo = new DefaultTableModel();
modelo.addColumn("Id compra");
        modelo.addColumn("Id producto");
        modelo.addColumn("Id proveedor");
        modelo.addColumn("cantidad de la compra");
        modelo.addColumn("Días compra");
        modelo.addColumn("Estado de la compra");
       Tbl_datos.setModel(modelo);
        String sql="";
        if(nombre.equals("")){
            sql="SELECT * FROM `compra`";
            
            
        
        }else{
            sql="SELECT * FROM `compra`";
        }
        String usuarios[]=new String[6];
        Statement set;
    try {
        set = con.createStatement();
        ResultSet result=set.executeQuery(sql);
        while(result.next()){
            usuarios[0]=result.getString(1);
            usuarios[1]=result.getString(2);
            usuarios[2]=result.getString(3);
            usuarios[3]=result.getString(4);
            usuarios[4]=result.getString(5);
            usuarios[5]=result.getString(6);

            modelo.addRow(usuarios);
        }
        Tbl_datos.setModel(modelo);
    } catch (SQLException ex) {
        Logger.getLogger(inventario.class.getName()).log(Level.SEVERE, null, ex);
    }
        
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tbl_datos;
    private javax.swing.JTextField cantidad_compra;
    private javax.swing.JLabel cantidadcompra;
    private javax.swing.JTextField dias_compra;
    private javax.swing.JLabel diascompra;
    private javax.swing.JTextField estado_compra;
    private javax.swing.JLabel estadocompra;
    private javax.swing.JTextField id_compra;
    private javax.swing.JTextField id_producto;
    private javax.swing.JTextField id_proveedor;
    private javax.swing.JLabel idcompra;
    private javax.swing.JLabel idproducto;
    private javax.swing.JLabel idproveedor;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
